# Generated by Django 4.1.7 on 2023-03-30 01:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contents", "0005_alter_article_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modificado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        verbose_name="Nome do Usuário",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, editable=False, max_length=254, null=True
                    ),
                ),
                ("text", models.TextField(editable=False, verbose_name="Comentario")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("published", "Aprovado"),
                            ("review", "Em Revisão"),
                            ("blocked", "Bloqueado"),
                        ],
                        default="published",
                        max_length=50,
                    ),
                ),
                ("like", models.PositiveIntegerField(default=0, editable=False)),
                ("spam", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contents.article",
                        verbose_name="Artigo Relacionado",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comments.comment",
                        verbose_name="Buscar Resposta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
            },
        ),
    ]
