# Generated by Django 4.1.7 on 2023-03-14 02:22

import app.accounts.models.reset_password
import app.common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modificado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Sobrenome"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={"unique": "Usuário com e-mail já existente."},
                        max_length=255,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="Acesso ao Dashboard?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="Ativo?",
                    ),
                ),
                (
                    "photo",
                    app.common.fields.ImageField(
                        help_text="Avatar",
                        upload_to="avatar-photo",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Documento"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cidade"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Estado"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Endereço"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="CEP"
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Dispositivo",
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("hash_token", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("admin", "Administrador"), ("customer", "Cliente")],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "agreed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "agreed_agent",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=250,
                        null=True,
                        verbose_name="Dispositivo",
                    ),
                ),
                (
                    "agreed_ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "unsubscribing_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Todos os usuários",
            },
        ),
        migrations.CreateModel(
            name="ResetPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=500)),
                (
                    "sending_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade de Solicitações"
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("agent", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "expires_in",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=app.accounts.models.reset_password.expires_in,
                        editable=False,
                        verbose_name="Token expira em",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitou Troca de Senha",
                "verbose_name_plural": "Solicitou Troca de Senha",
                "db_table": "accounts_resetpassword",
            },
        ),
        migrations.CreateModel(
            name="HistoryResetPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=500)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("agent", models.CharField(blank=True, max_length=500, null=True)),
                ("sending_attempts", models.PositiveIntegerField(default=0)),
                (
                    "expires_in",
                    models.DateTimeField(
                        blank=True,
                        default=app.accounts.models.reset_password.expires_in,
                        null=True,
                        verbose_name="Expira em",
                    ),
                ),
                (
                    "change_in",
                    models.DateTimeField(verbose_name="Criou uma nova senha às:"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Atualizado em"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Troca de Senha",
                "verbose_name_plural": "Histórico de Troca de Senhas",
                "db_table": "accounts_reset_history_password",
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Administradores",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
        ),
    ]
