# Generated by Django 4.1.7 on 2023-03-28 02:04

import app.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover",
            field=app.common.fields.ImageField(
                blank=True,
                help_text="Esta imagem será exibida dentro do artigo.",
                null=True,
                upload_to="articles-images",
                verbose_name="Imagem",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="read_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Visualizações"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="show_in_start",
            field=models.BooleanField(default=False, verbose_name="Exibir no inicio?"),
        ),
        migrations.AlterField(
            model_name="article",
            name="banner",
            field=app.common.fields.ImageField(
                help_text="Esta imagem será exibida como capa do artigo e banner",
                upload_to="articles-images",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="photo",
            field=app.common.fields.ImageField(
                upload_to="authors-profile", verbose_name="Foto"
            ),
        ),
    ]
